#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CinematicSkelMesh_Male_AR1003

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CinematicSkelMesh_Male_AR1003.BP_CinematicSkelMesh_Male_AR1003_C.ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003
// 0x0004 (0x0004 - 0x0000)
struct BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003) == 0x000004, "Wrong alignment on BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003");
static_assert(sizeof(BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003) == 0x000004, "Wrong size on BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003");
static_assert(offsetof(BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003, EntryPoint) == 0x000000, "Member 'BP_CinematicSkelMesh_Male_AR1003_C_ExecuteUbergraph_BP_CinematicSkelMesh_Male_AR1003::EntryPoint' has a wrong offset!");

}

