#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionTaskDestruction

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MissionTaskDestruction.BP_MissionTaskDestruction_C
// 0x0008 (0x0708 - 0x0700)
class ABP_MissionTaskDestruction_C final : public AM1MissionTaskActorDestruction
{
public:
	class UBillboardComponent*                    Billboard;                                         // 0x0700(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MissionTaskDestruction_C">();
	}
	static class ABP_MissionTaskDestruction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MissionTaskDestruction_C>();
	}
};
static_assert(alignof(ABP_MissionTaskDestruction_C) == 0x000008, "Wrong alignment on ABP_MissionTaskDestruction_C");
static_assert(sizeof(ABP_MissionTaskDestruction_C) == 0x000708, "Wrong size on ABP_MissionTaskDestruction_C");
static_assert(offsetof(ABP_MissionTaskDestruction_C, Billboard) == 0x000700, "Member 'ABP_MissionTaskDestruction_C::Billboard' has a wrong offset!");

}

