#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MIS_Prologue_Door_002

#include "Basic.hpp"

#include "BP_MIS_Prologue_Door_002_classes.hpp"
#include "BP_MIS_Prologue_Door_002_parameters.hpp"


namespace SDK
{

// Function BP_MIS_Prologue_Door_002.BP_MIS_Prologue_Door_002_C.BP_GetNavObstacleComponent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UShapeComponent*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UShapeComponent* ABP_MIS_Prologue_Door_002_C::BP_GetNavObstacleComponent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MIS_Prologue_Door_002_C", "BP_GetNavObstacleComponent");

	Params::BP_MIS_Prologue_Door_002_C_BP_GetNavObstacleComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

