#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SimpleTaskActor_CheckPoint

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SimpleTaskActor_CheckPoint.BP_SimpleTaskActor_CheckPoint_C
// 0x0010 (0x04A0 - 0x0490)
class ABP_SimpleTaskActor_CheckPoint_C final : public AM1SimpleTaskActor_CheckPoint
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Arrow;                                             // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SimpleTaskActor_CheckPoint(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SimpleTaskActor_CheckPoint_C">();
	}
	static class ABP_SimpleTaskActor_CheckPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SimpleTaskActor_CheckPoint_C>();
	}
};
static_assert(alignof(ABP_SimpleTaskActor_CheckPoint_C) == 0x000008, "Wrong alignment on ABP_SimpleTaskActor_CheckPoint_C");
static_assert(sizeof(ABP_SimpleTaskActor_CheckPoint_C) == 0x0004A0, "Wrong size on ABP_SimpleTaskActor_CheckPoint_C");
static_assert(offsetof(ABP_SimpleTaskActor_CheckPoint_C, UberGraphFrame) == 0x000490, "Member 'ABP_SimpleTaskActor_CheckPoint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_SimpleTaskActor_CheckPoint_C, Arrow) == 0x000498, "Member 'ABP_SimpleTaskActor_CheckPoint_C::Arrow' has a wrong offset!");

}

