#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcEtcBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_structs.hpp"
#include "M1Data_structs.hpp"


namespace SDK::Params
{

// Function CalcEtcBase.CalcEtcBase_C.ApplySkillATK
// 0x0938 (0x0938 - 0x0000)
struct CalcEtcBase_C_ApplySkillATK final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0008(0x0140)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	EM1ElementalDamageChannel                     ElementalChannel;                                  // 0x0148(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1SkillArcheType                             ArcheType;                                         // 0x0149(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       AddPower;                                          // 0x0150(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       AddAttack;                                         // 0x0158(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHittingPC;                                       // 0x0160(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       ArcheSkillAttack;                                  // 0x0168(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       ArcheSkillPower;                                   // 0x0170(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       ElementSkillAttack;                                // 0x0178(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       ElementSkillPower;                                 // 0x0180(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	EM1StatType                                   ATKStat;                                           // 0x0188(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue;       // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_1;     // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x01B0(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x01C8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01E0(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0230(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_2;     // 0x0280(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_3;     // 0x0290(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x02A0(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x02B8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x02D0(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x0320(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue;             // 0x0370(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue;       // 0x0378(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue;                   // 0x0380(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_1;                 // 0x0388(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_4;     // 0x0390(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_5;     // 0x03A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_4;          // 0x03B0(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_5;          // 0x03C8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x03E0(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_5;            // 0x0430(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0480(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1; // 0x0490(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_6;          // 0x04A0(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_7;          // 0x04B8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_6;            // 0x04D0(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_7;            // 0x0520(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_2;                 // 0x0570(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_6;     // 0x0578(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_8;          // 0x0588(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_8;            // 0x05A0(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue_1;           // 0x05F0(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x05F8(0x0010)(ReferenceParm)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_1;     // 0x0608(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0610(0x0018)()
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_2;     // 0x0628(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0630(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_3;     // 0x0640(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_4;     // 0x0648(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue_2;           // 0x0650(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_7;     // 0x0658(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_5;     // 0x0668(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_9;          // 0x0670(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_9;            // 0x0688(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue_3;           // 0x06D8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x06E0(0x0010)(ReferenceParm)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_6;     // 0x06F0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x06F8(0x0018)()
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue_4;           // 0x0710(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0718(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_3;                 // 0x0728(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_4;                 // 0x0730(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_7;     // 0x0738(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_8;     // 0x0740(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_5;                 // 0x0750(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_10;         // 0x0758(0x0018)()
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue;  // 0x0770(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_10;           // 0x0778(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1; // 0x07C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2; // 0x07D0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_6;                 // 0x07D8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3; // 0x07E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4; // 0x07E8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_9;     // 0x07F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_11;         // 0x0800(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_11;           // 0x0818(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_7;                 // 0x0868(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x0870(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x0880(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x0898(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_8;                 // 0x08A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_9;                 // 0x08B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_10;                // 0x08B8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_11;                // 0x08C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_12;                // 0x08C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_13;                // 0x08D0(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x08D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D9[0x7];                                      // 0x08D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_14;                // 0x08E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_15;                // 0x08E8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_16;                // 0x08F0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_17;                // 0x08F8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_18;                // 0x0900(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_19;                // 0x0908(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_20;                // 0x0910(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_21;                // 0x0918(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_22;                // 0x0920(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_23;                // 0x0928(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0930(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CalcEtcBase_C_ApplySkillATK) == 0x000008, "Wrong alignment on CalcEtcBase_C_ApplySkillATK");
static_assert(sizeof(CalcEtcBase_C_ApplySkillATK) == 0x000938, "Wrong size on CalcEtcBase_C_ApplySkillATK");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, Param) == 0x000000, "Member 'CalcEtcBase_C_ApplySkillATK::Param' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, DamageInfo) == 0x000008, "Member 'CalcEtcBase_C_ApplySkillATK::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ElementalChannel) == 0x000148, "Member 'CalcEtcBase_C_ApplySkillATK::ElementalChannel' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ArcheType) == 0x000149, "Member 'CalcEtcBase_C_ApplySkillATK::ArcheType' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, AddPower) == 0x000150, "Member 'CalcEtcBase_C_ApplySkillATK::AddPower' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, AddAttack) == 0x000158, "Member 'CalcEtcBase_C_ApplySkillATK::AddAttack' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, IsHittingPC) == 0x000160, "Member 'CalcEtcBase_C_ApplySkillATK::IsHittingPC' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ArcheSkillAttack) == 0x000168, "Member 'CalcEtcBase_C_ApplySkillATK::ArcheSkillAttack' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ArcheSkillPower) == 0x000170, "Member 'CalcEtcBase_C_ApplySkillATK::ArcheSkillPower' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ElementSkillAttack) == 0x000178, "Member 'CalcEtcBase_C_ApplySkillATK::ElementSkillAttack' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ElementSkillPower) == 0x000180, "Member 'CalcEtcBase_C_ApplySkillATK::ElementSkillPower' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, ATKStat) == 0x000188, "Member 'CalcEtcBase_C_ApplySkillATK::ATKStat' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue) == 0x000190, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_1) == 0x0001A0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue) == 0x0001B0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0001C8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData) == 0x0001E0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_1) == 0x000230, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_2) == 0x000280, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_3) == 0x000290, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_2) == 0x0002A0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_3) == 0x0002B8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_2) == 0x0002D0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_3) == 0x000320, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_ScaledIntegerOne_ReturnValue) == 0x000370, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_ScaledIntegerOne_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue) == 0x000378, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue) == 0x000380, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_1) == 0x000388, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_4) == 0x000390, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_5) == 0x0003A0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_4) == 0x0003B0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_5) == 0x0003C8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_4) == 0x0003E0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_5) == 0x000430, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_5' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000480, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1) == 0x000490, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_6) == 0x0004A0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_7) == 0x0004B8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_6) == 0x0004D0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_6' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_7) == 0x000520, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_7' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_2) == 0x000570, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_6) == 0x000578, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_8) == 0x000588, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_8) == 0x0005A0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_8' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_ScaledIntegerOne_ReturnValue_1) == 0x0005F0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_ScaledIntegerOne_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeArray_Array) == 0x0005F8, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_1) == 0x000608, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Format_ReturnValue) == 0x000610, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_2) == 0x000628, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_TextToString_ReturnValue) == 0x000630, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_3) == 0x000640, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_4) == 0x000648, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_ScaledIntegerOne_ReturnValue_2) == 0x000650, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_ScaledIntegerOne_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_7) == 0x000658, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_5) == 0x000668, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_9) == 0x000670, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_9) == 0x000688, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_9' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_ScaledIntegerOne_ReturnValue_3) == 0x0006D8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_ScaledIntegerOne_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeArray_Array_1) == 0x0006E0, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_6) == 0x0006F0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Format_ReturnValue_1) == 0x0006F8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_ScaledIntegerOne_ReturnValue_4) == 0x000710, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_ScaledIntegerOne_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_TextToString_ReturnValue_1) == 0x000718, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_3) == 0x000728, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_4) == 0x000730, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Add_ScaledIntScaledInt_ReturnValue_7) == 0x000738, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Add_ScaledIntScaledInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_8) == 0x000740, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_5) == 0x000750, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_10) == 0x000758, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue) == 0x000770, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_10) == 0x000778, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_10' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1) == 0x0007C8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2) == 0x0007D0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_6) == 0x0007D8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3) == 0x0007E0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4) == 0x0007E8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_ScaledIntToString_ReturnValue_9) == 0x0007F0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_ScaledIntToString_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_StringToText_ReturnValue_11) == 0x000800, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_StringToText_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeStruct_FormatArgumentData_11) == 0x000818, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeStruct_FormatArgumentData_11' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_7) == 0x000868, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_MakeArray_Array_2) == 0x000870, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Format_ReturnValue_2) == 0x000880, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Format_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_Conv_TextToString_ReturnValue_2) == 0x000898, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_8) == 0x0008A8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_9) == 0x0008B0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_10) == 0x0008B8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_11) == 0x0008C0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_12) == 0x0008C8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_13) == 0x0008D0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_SwitchEnum_CmpSuccess) == 0x0008D8, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_14) == 0x0008E0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_15) == 0x0008E8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_16) == 0x0008F0, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_17) == 0x0008F8, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_18) == 0x000900, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_18' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_19) == 0x000908, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_19' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_20) == 0x000910, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_20' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_21) == 0x000918, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_21' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_22) == 0x000920, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_22' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, CallFunc_GetRefStat_ReturnValue_23) == 0x000928, "Member 'CalcEtcBase_C_ApplySkillATK::CallFunc_GetRefStat_ReturnValue_23' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillATK, K2Node_SwitchEnum_CmpSuccess_1) == 0x000930, "Member 'CalcEtcBase_C_ApplySkillATK::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");

// Function CalcEtcBase.CalcEtcBase_C.ApplySkillCost
// 0x03C0 (0x03C0 - 0x0000)
struct CalcEtcBase_C_ApplySkillCost final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0008(0x0140)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          IsRatio;                                           // 0x0148(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Value;                                             // 0x0150(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1StatType                                   MaxStat;                                           // 0x0158(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIgnoreCoefficient;                                // 0x0159(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_BoolToText_ReturnValue;              // 0x0160(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0178(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue;       // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x01D8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x01F0(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue;             // 0x0240(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue;                   // 0x0248(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue;       // 0x0250(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue;                    // 0x0258(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_1;                 // 0x0260(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue;  // 0x0268(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1; // 0x0270(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_2;                 // 0x0278(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_1;     // 0x0280(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0290(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x02A8(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x02F8(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0348(0x0010)(ReferenceParm)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_1;                  // 0x0358(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0360(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0378(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue_3;                 // 0x0388(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue_1;           // 0x0398(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue_1;     // 0x03A0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2; // 0x03A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       K2Node_Select_Default;                             // 0x03B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast;           // 0x03B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast_1;         // 0x03BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CalcEtcBase_C_ApplySkillCost) == 0x000008, "Wrong alignment on CalcEtcBase_C_ApplySkillCost");
static_assert(sizeof(CalcEtcBase_C_ApplySkillCost) == 0x0003C0, "Wrong size on CalcEtcBase_C_ApplySkillCost");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, Param) == 0x000000, "Member 'CalcEtcBase_C_ApplySkillCost::Param' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, DamageInfo) == 0x000008, "Member 'CalcEtcBase_C_ApplySkillCost::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, IsRatio) == 0x000148, "Member 'CalcEtcBase_C_ApplySkillCost::IsRatio' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, Value) == 0x000150, "Member 'CalcEtcBase_C_ApplySkillCost::Value' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, MaxStat) == 0x000158, "Member 'CalcEtcBase_C_ApplySkillCost::MaxStat' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, bIgnoreCoefficient) == 0x000159, "Member 'CalcEtcBase_C_ApplySkillCost::bIgnoreCoefficient' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_BoolToText_ReturnValue) == 0x000160, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_BoolToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_MakeStruct_FormatArgumentData) == 0x000178, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_ScaledIntToString_ReturnValue) == 0x0001C8, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_ScaledIntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_StringToText_ReturnValue) == 0x0001D8, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_MakeStruct_FormatArgumentData_1) == 0x0001F0, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_ScaledIntegerOne_ReturnValue) == 0x000240, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_ScaledIntegerOne_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_GetRefStat_ReturnValue) == 0x000248, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_GetRefStat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Add_ScaledIntScaledInt_ReturnValue) == 0x000250, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Add_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_FromFloat_ReturnValue) == 0x000258, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_FromFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_GetRefStat_ReturnValue_1) == 0x000260, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_GetRefStat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue) == 0x000268, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1) == 0x000270, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_GetRefStat_ReturnValue_2) == 0x000278, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_GetRefStat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_ScaledIntToString_ReturnValue_1) == 0x000280, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_ScaledIntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000290, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_MakeStruct_FormatArgumentData_2) == 0x0002A8, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_MakeStruct_FormatArgumentData_3) == 0x0002F8, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_MakeArray_Array) == 0x000348, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_FromFloat_ReturnValue_1) == 0x000358, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_FromFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Format_ReturnValue) == 0x000360, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Conv_TextToString_ReturnValue) == 0x000378, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_GetRefStat_ReturnValue_3) == 0x000388, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_GetRefStat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, Temp_bool_Variable) == 0x000390, "Member 'CalcEtcBase_C_ApplySkillCost::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_ScaledIntegerOne_ReturnValue_1) == 0x000398, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_ScaledIntegerOne_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Add_ScaledIntScaledInt_ReturnValue_1) == 0x0003A0, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Add_ScaledIntScaledInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2) == 0x0003A8, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, K2Node_Select_Default) == 0x0003B0, "Member 'CalcEtcBase_C_ApplySkillCost::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_FromFloat_InValue_ImplicitCast) == 0x0003B8, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_FromFloat_InValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_ApplySkillCost, CallFunc_FromFloat_InValue_ImplicitCast_1) == 0x0003BC, "Member 'CalcEtcBase_C_ApplySkillCost::CallFunc_FromFloat_InValue_ImplicitCast_1' has a wrong offset!");

// Function CalcEtcBase.CalcEtcBase_C.DoCalculation
// 0x0158 (0x0158 - 0x0000)
struct CalcEtcBase_C_DoCalculation final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0008(0x0140)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FM1AbilityOpExecCalcOutput             Output;                                            // 0x0148(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(CalcEtcBase_C_DoCalculation) == 0x000008, "Wrong alignment on CalcEtcBase_C_DoCalculation");
static_assert(sizeof(CalcEtcBase_C_DoCalculation) == 0x000158, "Wrong size on CalcEtcBase_C_DoCalculation");
static_assert(offsetof(CalcEtcBase_C_DoCalculation, Param) == 0x000000, "Member 'CalcEtcBase_C_DoCalculation::Param' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_DoCalculation, DamageInfo) == 0x000008, "Member 'CalcEtcBase_C_DoCalculation::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_DoCalculation, Output) == 0x000148, "Member 'CalcEtcBase_C_DoCalculation::Output' has a wrong offset!");

// Function CalcEtcBase.CalcEtcBase_C.Execute
// 0x0348 (0x0348 - 0x0000)
struct CalcEtcBase_C_Execute final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1AbilityOpExecCalcOutput             Output;                                            // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0018(0x0140)(Edit, BlueprintVisible, ContainsInstancedReference)
	struct FM1CalcDamageInfo                      CallFunc_MakeCalcDamageInfo_ReturnValue;           // 0x0158(0x0140)(ContainsInstancedReference)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0298(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x02A8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x02C0(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0310(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0320(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0338(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(CalcEtcBase_C_Execute) == 0x000008, "Wrong alignment on CalcEtcBase_C_Execute");
static_assert(sizeof(CalcEtcBase_C_Execute) == 0x000348, "Wrong size on CalcEtcBase_C_Execute");
static_assert(offsetof(CalcEtcBase_C_Execute, Param) == 0x000000, "Member 'CalcEtcBase_C_Execute::Param' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, Output) == 0x000008, "Member 'CalcEtcBase_C_Execute::Output' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, DamageInfo) == 0x000018, "Member 'CalcEtcBase_C_Execute::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, CallFunc_MakeCalcDamageInfo_ReturnValue) == 0x000158, "Member 'CalcEtcBase_C_Execute::CallFunc_MakeCalcDamageInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, CallFunc_GetDisplayName_ReturnValue) == 0x000298, "Member 'CalcEtcBase_C_Execute::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, CallFunc_Conv_StringToText_ReturnValue) == 0x0002A8, "Member 'CalcEtcBase_C_Execute::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, K2Node_MakeStruct_FormatArgumentData) == 0x0002C0, "Member 'CalcEtcBase_C_Execute::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, K2Node_MakeArray_Array) == 0x000310, "Member 'CalcEtcBase_C_Execute::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, CallFunc_Format_ReturnValue) == 0x000320, "Member 'CalcEtcBase_C_Execute::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcEtcBase_C_Execute, CallFunc_Conv_TextToString_ReturnValue) == 0x000338, "Member 'CalcEtcBase_C_Execute::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");

}

