#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcShieldReflectDamage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_structs.hpp"
#include "M1Data_structs.hpp"


namespace SDK::Params
{

// Function CalcShieldReflectDamage.CalcShieldReflectDamage_C.AjaxReflectDamage
// 0x06F8 (0x06F8 - 0x0000)
struct CalcShieldReflectDamage_C_AjaxReflectDamage final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0008(0x0140)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FM1ScaledInteger                       FinalDEFRatio;                                     // 0x0148(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       SourceDEF;                                         // 0x0150(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       MaxDEFRatio;                                       // 0x0158(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       SourceDEFRatio;                                    // 0x0160(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       TotalReflectPower;                                 // 0x0168(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue;                    // 0x0170(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue;          // 0x0178(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_1;        // 0x0188(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0198(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x01B0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01C8(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0218(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue;       // 0x0268(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_1;     // 0x0278(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0288(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x02A0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x02B8(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x0308(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_2;     // 0x0358(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0368(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_4;          // 0x0378(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_5;          // 0x0390(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x03A8(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_5;            // 0x03F8(0x0050)(HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue_3;     // 0x0448(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_6;          // 0x0458(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_6;            // 0x0470(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_1;                  // 0x04C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_2;                  // 0x04C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_3;                  // 0x04D0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue;  // 0x04D8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Divide_ScaledIntScaledInt_ReturnValue;    // 0x04E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_2;        // 0x04E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerClamp_ReturnValue;           // 0x04F8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_7;          // 0x0500(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_7;            // 0x0518(0x0050)(HasGetValueTypeHash)
	float                                         CallFunc_Conv_ScaledIntToFloat_ReturnValue;        // 0x0568(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_56C[0x4];                                      // 0x056C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_4;                  // 0x0570(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_5;                  // 0x0578(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue; // 0x0580(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_581[0x7];                                      // 0x0581(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_GetDEFLimitConst_ReturnValue;             // 0x0588(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_ScaledIntToFloat_ReturnValue_1;      // 0x0590(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_594[0x4];                                      // 0x0594(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_GetDEFScaleConst_ReturnValue;             // 0x0598(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_ScaledIntToFloat_ReturnValue_2;      // 0x05A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5A4[0x4];                                      // 0x05A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x05A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_ReturnValue;                 // 0x05B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Sqrt_A_ImplicitCast;                      // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x05C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x05D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x05D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast_1;   // 0x05E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_8;          // 0x05E8(0x0018)()
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_6;                  // 0x0600(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_8;            // 0x0608(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0658(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0668(0x0018)()
	struct FM1ScaledInteger                       CallFunc_GetRefStat_ReturnValue;                   // 0x0680(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0688(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1; // 0x0698(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromInt_ReturnValue;                      // 0x06A0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_7;                  // 0x06A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2; // 0x06B0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Add_ScaledIntScaledInt_ReturnValue;       // 0x06B8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3; // 0x06C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4; // 0x06C8(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast;           // 0x06D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast_1;         // 0x06D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_FnA_ImplicitCast;            // 0x06D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_DEFLimitConst_ImplicitCast;  // 0x06E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_MathExpression_DEFScaleConst_ImplicitCast;  // 0x06E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast_2;         // 0x06F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast_3;         // 0x06F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CalcShieldReflectDamage_C_AjaxReflectDamage) == 0x000008, "Wrong alignment on CalcShieldReflectDamage_C_AjaxReflectDamage");
static_assert(sizeof(CalcShieldReflectDamage_C_AjaxReflectDamage) == 0x0006F8, "Wrong size on CalcShieldReflectDamage_C_AjaxReflectDamage");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, Param) == 0x000000, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::Param' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, DamageInfo) == 0x000008, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, FinalDEFRatio) == 0x000148, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::FinalDEFRatio' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, SourceDEF) == 0x000150, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::SourceDEF' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, MaxDEFRatio) == 0x000158, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::MaxDEFRatio' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, SourceDEFRatio) == 0x000160, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::SourceDEFRatio' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, TotalReflectPower) == 0x000168, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::TotalReflectPower' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue) == 0x000170, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_DoubleToString_ReturnValue) == 0x000178, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_DoubleToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_DoubleToString_ReturnValue_1) == 0x000188, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_DoubleToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue) == 0x000198, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0001B0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData) == 0x0001C8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_1) == 0x000218, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToString_ReturnValue) == 0x000268, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToString_ReturnValue_1) == 0x000278, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_2) == 0x000288, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_3) == 0x0002A0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_2) == 0x0002B8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_3) == 0x000308, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToString_ReturnValue_2) == 0x000358, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_IntToString_ReturnValue) == 0x000368, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_4) == 0x000378, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_5) == 0x000390, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_4) == 0x0003A8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_4' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_5) == 0x0003F8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_5' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToString_ReturnValue_3) == 0x000448, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToString_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_6) == 0x000458, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_6) == 0x000470, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_6' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_1) == 0x0004C0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_2) == 0x0004C8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_3) == 0x0004D0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue) == 0x0004D8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Divide_ScaledIntScaledInt_ReturnValue) == 0x0004E0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Divide_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_DoubleToString_ReturnValue_2) == 0x0004E8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_DoubleToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_ScaledIntegerClamp_ReturnValue) == 0x0004F8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_ScaledIntegerClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_7) == 0x000500, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_7) == 0x000518, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_7' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToFloat_ReturnValue) == 0x000568, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_4) == 0x000570, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_5) == 0x000578, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue) == 0x000580, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_GetDEFLimitConst_ReturnValue) == 0x000588, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_GetDEFLimitConst_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToFloat_ReturnValue_1) == 0x000590, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_GetDEFScaleConst_ReturnValue) == 0x000598, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_GetDEFScaleConst_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_ScaledIntToFloat_ReturnValue_2) == 0x0005A0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_ScaledIntToFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x0005A8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MathExpression_ReturnValue) == 0x0005B8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MathExpression_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Sqrt_A_ImplicitCast) == 0x0005C0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Sqrt_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0005C8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x0005D0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x0005D8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_DoubleDouble_B_ImplicitCast_1) == 0x0005E0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_DoubleDouble_B_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_StringToText_ReturnValue_8) == 0x0005E8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_StringToText_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_6) == 0x000600, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeStruct_FormatArgumentData_8) == 0x000608, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeStruct_FormatArgumentData_8' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MakeArray_Array) == 0x000658, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Format_ReturnValue) == 0x000668, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_GetRefStat_ReturnValue) == 0x000680, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_GetRefStat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Conv_TextToString_ReturnValue) == 0x000688, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1) == 0x000698, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromInt_ReturnValue) == 0x0006A0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_ReturnValue_7) == 0x0006A8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2) == 0x0006B0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Add_ScaledIntScaledInt_ReturnValue) == 0x0006B8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Add_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3) == 0x0006C0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4) == 0x0006C8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_InValue_ImplicitCast) == 0x0006D0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_InValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_InValue_ImplicitCast_1) == 0x0006D4, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_InValue_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MathExpression_FnA_ImplicitCast) == 0x0006D8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MathExpression_FnA_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MathExpression_DEFLimitConst_ImplicitCast) == 0x0006E0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MathExpression_DEFLimitConst_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, K2Node_MathExpression_DEFScaleConst_ImplicitCast) == 0x0006E8, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::K2Node_MathExpression_DEFScaleConst_ImplicitCast' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_InValue_ImplicitCast_2) == 0x0006F0, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_InValue_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_AjaxReflectDamage, CallFunc_FromFloat_InValue_ImplicitCast_3) == 0x0006F4, "Member 'CalcShieldReflectDamage_C_AjaxReflectDamage::CallFunc_FromFloat_InValue_ImplicitCast_3' has a wrong offset!");

// Function CalcShieldReflectDamage.CalcShieldReflectDamage_C.DoCalculation
// 0x0238 (0x0238 - 0x0000)
struct CalcShieldReflectDamage_C_DoCalculation final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1CalcDamageInfo                      DamageInfo;                                        // 0x0008(0x0140)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FM1ScaledInteger                       DEFRatio;                                          // 0x0148(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_ScaledIntToString_ReturnValue;       // 0x0150(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue;                    // 0x0160(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0168(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0180(0x0050)(HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue_1;                  // 0x01D0(0x0008)(NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01D8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01E8(0x0018)()
	struct FM1ScaledInteger                       CallFunc_ScaledIntegerOne_ReturnValue;             // 0x0200(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0208(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_DetermineElemetalDEF_ElementalDEF;        // 0x0218(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Subtract_ScaledIntScaledInt_ReturnValue;  // 0x0220(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_Multiply_ScaledIntScaledInt_ReturnValue;  // 0x0228(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue; // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CalcShieldReflectDamage_C_DoCalculation) == 0x000008, "Wrong alignment on CalcShieldReflectDamage_C_DoCalculation");
static_assert(sizeof(CalcShieldReflectDamage_C_DoCalculation) == 0x000238, "Wrong size on CalcShieldReflectDamage_C_DoCalculation");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, Param) == 0x000000, "Member 'CalcShieldReflectDamage_C_DoCalculation::Param' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, DamageInfo) == 0x000008, "Member 'CalcShieldReflectDamage_C_DoCalculation::DamageInfo' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, DEFRatio) == 0x000148, "Member 'CalcShieldReflectDamage_C_DoCalculation::DEFRatio' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Conv_ScaledIntToString_ReturnValue) == 0x000150, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Conv_ScaledIntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_FromFloat_ReturnValue) == 0x000160, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_FromFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Conv_StringToText_ReturnValue) == 0x000168, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, K2Node_MakeStruct_FormatArgumentData) == 0x000180, "Member 'CalcShieldReflectDamage_C_DoCalculation::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_FromFloat_ReturnValue_1) == 0x0001D0, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_FromFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, K2Node_MakeArray_Array) == 0x0001D8, "Member 'CalcShieldReflectDamage_C_DoCalculation::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Format_ReturnValue) == 0x0001E8, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_ScaledIntegerOne_ReturnValue) == 0x000200, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_ScaledIntegerOne_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Conv_TextToString_ReturnValue) == 0x000208, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_DetermineElemetalDEF_ElementalDEF) == 0x000218, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_DetermineElemetalDEF_ElementalDEF' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Subtract_ScaledIntScaledInt_ReturnValue) == 0x000220, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Subtract_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_Multiply_ScaledIntScaledInt_ReturnValue) == 0x000228, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_Multiply_ScaledIntScaledInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CalcShieldReflectDamage_C_DoCalculation, CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue) == 0x000230, "Member 'CalcShieldReflectDamage_C_DoCalculation::CallFunc_LessEqual_ScaledIntScaledInt_ReturnValue' has a wrong offset!");

}

