#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PL_GameStart_Viessa

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PL_GameStart_Viessa.PL_GameStart_Viessa_C
// 0x0000 (0x03A0 - 0x03A0)
class APL_GameStart_Viessa_C final : public AM1LevelSequenceActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PL_GameStart_Viessa_C">();
	}
	static class APL_GameStart_Viessa_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APL_GameStart_Viessa_C>();
	}
};
static_assert(alignof(APL_GameStart_Viessa_C) == 0x000008, "Wrong alignment on APL_GameStart_Viessa_C");
static_assert(sizeof(APL_GameStart_Viessa_C) == 0x0003A0, "Wrong size on APL_GameStart_Viessa_C");

}

