#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PL_Select_1102P_Master

#include "Basic.hpp"

#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PL_Select_1102P_Master.PL_Select_1102P_Master_DirectorBP_C
// 0x0000 (0x0038 - 0x0038)
class UPL_Select_1102P_Master_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PL_Select_1102P_Master_DirectorBP_C">();
	}
	static class UPL_Select_1102P_Master_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPL_Select_1102P_Master_DirectorBP_C>();
	}
};
static_assert(alignof(UPL_Select_1102P_Master_DirectorBP_C) == 0x000008, "Wrong alignment on UPL_Select_1102P_Master_DirectorBP_C");
static_assert(sizeof(UPL_Select_1102P_Master_DirectorBP_C) == 0x000038, "Wrong size on UPL_Select_1102P_Master_DirectorBP_C");

}

