#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PL_S00_C070

#include "Basic.hpp"

#include "PL_S00_C070_classes.hpp"
#include "PL_S00_C070_parameters.hpp"


namespace SDK
{

// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.AJax_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAJax_C*                          Ajax                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::AJax_Event(class AAJax_C* Ajax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "AJax_Event");

	Params::PL_S00_C070_DirectorBP_C_AJax_Event Parms{};

	Parms.Ajax = Ajax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.ExecuteUbergraph_PL_S00_C070_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::ExecuteUbergraph_PL_S00_C070_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "ExecuteUbergraph_PL_S00_C070_DirectorBP");

	Params::PL_S00_C070_DirectorBP_C_ExecuteUbergraph_PL_S00_C070_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.Lepic_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALepic_C*                         Lepic                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::Lepic_Event(class ALepic_C* Lepic)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "Lepic_Event");

	Params::PL_S00_C070_DirectorBP_C_Lepic_Event Parms{};

	Parms.Lepic = Lepic;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALepic_C*                         Lepic                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP(class ALepic_C* Lepic)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP");

	Params::PL_S00_C070_DirectorBP_C_SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP Parms{};

	Parms.Lepic = Lepic;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAJax_C*                          Ajax                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_0(class AAJax_C* Ajax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_0");

	Params::PL_S00_C070_DirectorBP_C_SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_0 Parms{};

	Parms.Ajax = Ajax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AViessa_C*                        Viessa                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_1(class AViessa_C* Viessa)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_1");

	Params::PL_S00_C070_DirectorBP_C_SequenceEvent__ENTRYPOINTPL_S00_C070_DirectorBP_1 Parms{};

	Parms.Viessa = Viessa;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PL_S00_C070.PL_S00_C070_DirectorBP_C.Viessa_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AViessa_C*                        Viessa                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPL_S00_C070_DirectorBP_C::Viessa_Event(class AViessa_C* Viessa)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PL_S00_C070_DirectorBP_C", "Viessa_Event");

	Params::PL_S00_C070_DirectorBP_C_Viessa_Event Parms{};

	Parms.Viessa = Viessa;

	UObject::ProcessEvent(Func, &Parms);
}

}

