#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PL_World_View

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PL_World_View.PL_World_View_C
// 0x0000 (0x03A0 - 0x03A0)
class APL_World_View_C final : public AM1LevelSequenceActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PL_World_View_C">();
	}
	static class APL_World_View_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APL_World_View_C>();
	}
};
static_assert(alignof(APL_World_View_C) == 0x000008, "Wrong alignment on APL_World_View_C");
static_assert(sizeof(APL_World_View_C) == 0x0003A0, "Wrong size on APL_World_View_C");

}

