#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrologueBunny_BP

#include "Basic.hpp"

#include "Main_structs.hpp"


namespace SDK
{

// ScriptStruct PrologueBunny_BP.PrologueBunny_BP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01E0 - 0x01E0)
struct PrologueBunny_BP::FAnimBlueprintGeneratedConstantData final : public Main::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(PrologueBunny_BP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on PrologueBunny_BP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(PrologueBunny_BP::FAnimBlueprintGeneratedConstantData) == 0x0001E0, "Wrong size on PrologueBunny_BP::FAnimBlueprintGeneratedConstantData");

}

