#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Button_Tooltip_Default_V01

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "UI_Button_Tooltip_Default_A_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Button_Tooltip_Default_V01.UI_Button_Tooltip_Default_V01_C
// 0x0008 (0x0758 - 0x0750)
class UUI_Button_Tooltip_Default_V01_C final : public UUI_Button_Tooltip_Default_A_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_Button_Tooltip_Default_V01_C;    // 0x0750(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UI_Button_Tooltip_Default_V01(int32 EntryPoint);
	void OnEventWidgetOpen(EM1WidgetAnimDirection InDirection);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Button_Tooltip_Default_V01_C">();
	}
	static class UUI_Button_Tooltip_Default_V01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Button_Tooltip_Default_V01_C>();
	}
};
static_assert(alignof(UUI_Button_Tooltip_Default_V01_C) == 0x000008, "Wrong alignment on UUI_Button_Tooltip_Default_V01_C");
static_assert(sizeof(UUI_Button_Tooltip_Default_V01_C) == 0x000758, "Wrong size on UUI_Button_Tooltip_Default_V01_C");
static_assert(offsetof(UUI_Button_Tooltip_Default_V01_C, UberGraphFrame_UI_Button_Tooltip_Default_V01_C) == 0x000750, "Member 'UUI_Button_Tooltip_Default_V01_C::UberGraphFrame_UI_Button_Tooltip_Default_V01_C' has a wrong offset!");

}

