#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_EternityDungeonInteraction

#include "Basic.hpp"

#include "UI_Game_EternityDungeonInteraction_classes.hpp"
#include "UI_Game_EternityDungeonInteraction_parameters.hpp"


namespace SDK
{

// Function UI_Game_EternityDungeonInteraction.UI_Game_EternityDungeonInteraction_C.ExecuteUbergraph_UI_Game_EternityDungeonInteraction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Game_EternityDungeonInteraction_C::ExecuteUbergraph_UI_Game_EternityDungeonInteraction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_EternityDungeonInteraction_C", "ExecuteUbergraph_UI_Game_EternityDungeonInteraction");

	Params::UI_Game_EternityDungeonInteraction_C_ExecuteUbergraph_UI_Game_EternityDungeonInteraction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_EternityDungeonInteraction.UI_Game_EternityDungeonInteraction_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Game_EternityDungeonInteraction_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_EternityDungeonInteraction_C", "PreConstruct");

	Params::UI_Game_EternityDungeonInteraction_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_EternityDungeonInteraction.UI_Game_EternityDungeonInteraction_C.Set Color
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Game_EternityDungeonInteraction_C::Set_Color(uint8 Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_EternityDungeonInteraction_C", "Set Color");

	Params::UI_Game_EternityDungeonInteraction_C_Set_Color Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);
}

}

