#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Popup_MoviePlayer

#include "Basic.hpp"

#include "UI_Popup_MoviePlayer_classes.hpp"
#include "UI_Popup_MoviePlayer_parameters.hpp"


namespace SDK
{

// Function UI_Popup_MoviePlayer.UI_Popup_MoviePlayer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Popup_MoviePlayer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Popup_MoviePlayer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Popup_MoviePlayer.UI_Popup_MoviePlayer_C.ExecuteUbergraph_UI_Popup_MoviePlayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Popup_MoviePlayer_C::ExecuteUbergraph_UI_Popup_MoviePlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Popup_MoviePlayer_C", "ExecuteUbergraph_UI_Popup_MoviePlayer");

	Params::UI_Popup_MoviePlayer_C_ExecuteUbergraph_UI_Popup_MoviePlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Popup_MoviePlayer.UI_Popup_MoviePlayer_C.PlayAkSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAkResult                               Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Popup_MoviePlayer_C::PlayAkSound(EAkResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Popup_MoviePlayer_C", "PlayAkSound");

	Params::UI_Popup_MoviePlayer_C_PlayAkSound Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}

}

