#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UltimateFreyma_Run6_StackCount

#include "Basic.hpp"

#include "StatBased_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UltimateFreyma_Run6_StackCount.UltimateFreyma_Run6_StackCount_C
// 0x0010 (0x0108 - 0x00F8)
class UUltimateFreyma_Run6_StackCount_C final : public UStatBased_C
{
public:
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Value;                                             // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         StackCount;                                        // 0x0100(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FM1ScaledInteger CalculateValue(const struct FM1AbilityOpCalcParam& Param) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UltimateFreyma_Run6_StackCount_C">();
	}
	static class UUltimateFreyma_Run6_StackCount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUltimateFreyma_Run6_StackCount_C>();
	}
};
static_assert(alignof(UUltimateFreyma_Run6_StackCount_C) == 0x000008, "Wrong alignment on UUltimateFreyma_Run6_StackCount_C");
static_assert(sizeof(UUltimateFreyma_Run6_StackCount_C) == 0x000108, "Wrong size on UUltimateFreyma_Run6_StackCount_C");
static_assert(offsetof(UUltimateFreyma_Run6_StackCount_C, Value) == 0x0000F8, "Member 'UUltimateFreyma_Run6_StackCount_C::Value' has a wrong offset!");
static_assert(offsetof(UUltimateFreyma_Run6_StackCount_C, StackCount) == 0x000100, "Member 'UUltimateFreyma_Run6_StackCount_C::StackCount' has a wrong offset!");

}

