#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Viessa_Active02_FrostFog

#include "Basic.hpp"

#include "SplineAOEBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Viessa_Active02_FrostFog.Viessa_Active02_FrostFog_C
// 0x0008 (0x0898 - 0x0890)
class AViessa_Active02_FrostFog_C final : public ASplineAOEBase_C
{
public:
	int32                                         IceBindLevelByFrostFog;                            // 0x0890(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnEvaluateCondition();
	void OnBeginOverlap(class AActor* OverlapActor);
	void ExecutePeriodDamage(class AActor* TargetActor_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Viessa_Active02_FrostFog_C">();
	}
	static class AViessa_Active02_FrostFog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AViessa_Active02_FrostFog_C>();
	}
};
static_assert(alignof(AViessa_Active02_FrostFog_C) == 0x000008, "Wrong alignment on AViessa_Active02_FrostFog_C");
static_assert(sizeof(AViessa_Active02_FrostFog_C) == 0x000898, "Wrong size on AViessa_Active02_FrostFog_C");
static_assert(offsetof(AViessa_Active02_FrostFog_C, IceBindLevelByFrostFog) == 0x000890, "Member 'AViessa_Active02_FrostFog_C::IceBindLevelByFrostFog' has a wrong offset!");

}

