#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldView_Sequence

#include "Basic.hpp"

#include "WorldView_Sequence_classes.hpp"
#include "WorldView_Sequence_parameters.hpp"


namespace SDK
{

// Function WorldView_Sequence.WorldView_Sequence_DirectorBP_C.Event_ShowMovieWidget
// (BlueprintCallable, BlueprintEvent)

void UWorldView_Sequence_DirectorBP_C::Event_ShowMovieWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldView_Sequence_DirectorBP_C", "Event_ShowMovieWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WorldView_Sequence.WorldView_Sequence_DirectorBP_C.ExecuteUbergraph_WorldView_Sequence_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWorldView_Sequence_DirectorBP_C::ExecuteUbergraph_WorldView_Sequence_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldView_Sequence_DirectorBP_C", "ExecuteUbergraph_WorldView_Sequence_DirectorBP");

	Params::WorldView_Sequence_DirectorBP_C_ExecuteUbergraph_WorldView_Sequence_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WorldView_Sequence.WorldView_Sequence_DirectorBP_C.SequenceEvent__ENTRYPOINTWorldView_Sequence_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)

void UWorldView_Sequence_DirectorBP_C::SequenceEvent__ENTRYPOINTWorldView_Sequence_DirectorBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WorldView_Sequence_DirectorBP_C", "SequenceEvent__ENTRYPOINTWorldView_Sequence_DirectorBP");

	UObject::ProcessEvent(Func, nullptr);
}

}

