#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldView_Sequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WorldView_Sequence.WorldView_Sequence_DirectorBP_C
// 0x0008 (0x0040 - 0x0038)
class UWorldView_Sequence_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Event_ShowMovieWidget();
	void ExecuteUbergraph_WorldView_Sequence_DirectorBP(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTWorldView_Sequence_DirectorBP();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WorldView_Sequence_DirectorBP_C">();
	}
	static class UWorldView_Sequence_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWorldView_Sequence_DirectorBP_C>();
	}
};
static_assert(alignof(UWorldView_Sequence_DirectorBP_C) == 0x000008, "Wrong alignment on UWorldView_Sequence_DirectorBP_C");
static_assert(sizeof(UWorldView_Sequence_DirectorBP_C) == 0x000040, "Wrong size on UWorldView_Sequence_DirectorBP_C");
static_assert(offsetof(UWorldView_Sequence_DirectorBP_C, UberGraphFrame) == 0x000038, "Member 'UWorldView_Sequence_DirectorBP_C::UberGraphFrame' has a wrong offset!");

}

